# Generated by Django 3.1.2 on 2020-10-17 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productgroup',
            old_name='percentage_comission',
            new_name='percentage_commission',
        ),
    ]
